version: "3.9"

services:
  dn42-wiki-go:
    build: .
    image: dn42-wiki-go:latest
    # ports:
    #   - "8080:8080"
    volumes:
      - ./config.json:/app/config.json:ro
      - ./data/dist:/app/dist
      - ./data/repo:/app/repo
    restart: always
    init: true
    command: ["--config", "/app/config.json"]
