name: Build and Release Go Binaries

on:
  release:
    types: [published]

jobs:
  compile:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        goos: [linux, windows, darwin]
        goarch: [386, amd64, arm64]
        exclude:
          - goarch: 386
            goos: darwin

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: 1.25

      - name: Capture build metadata
        run: echo "GIT_COMMIT=$(git rev-parse --short HEAD)" >> $GITHUB_ENV

      - name: Build dependencies
        working-directory: ./src
        run: go mod tidy && go get

      - name: Build binaries
        working-directory: ./src
        run: GOOS=${{ matrix.goos }} GOARCH=${{ matrix.goarch }} go build -ldflags="-s -w -X main.GIT_COMMIT=${GIT_COMMIT}" -o dn42-wiki-go_${{ matrix.goos }}_${{ matrix.goarch }}

      - name: Upload binaries
        uses: actions/upload-artifact@v4
        with:
          name: dn42-wiki-go_${{ matrix.goos }}_${{ matrix.goarch }}
          path: ./src/dn42-wiki-go_${{ matrix.goos }}_${{ matrix.goarch }}

  release:
    needs: compile
    name: Release to GitHub
    runs-on: ubuntu-latest
    strategy:
      matrix:
        goos: [linux, windows, darwin]
        goarch: [386, amd64, arm64]
        exclude:
          - goarch: 386
            goos: darwin
    steps:
      - uses: actions/download-artifact@v4
        with:
          name: dn42-wiki-go_${{ matrix.goos }}_${{ matrix.goarch }}
          path: dn42-wiki-go_${{ matrix.goos }}_${{ matrix.goarch }}

      - uses: softprops/action-gh-release@v2
        with:
          files: dn42-wiki-go_${{ matrix.goos }}_${{ matrix.goarch }}/dn42-wiki-go_${{ matrix.goos }}_${{ matrix.goarch }}
